name: 'Test Core Spec'
description: 'Test Core Spec'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./core
        filename: CoreBuild.zip

    - name: Install Dependencies at the root of the repo
      run: npm ci
      shell: bash

    - name: Test
      run: npm run test.spec -- --ci
      shell: bash
      working-directory: ./core
